### ISSUE TITLE
URLhaus link updates

### ISSUE THREAD

**Issue by RicoHeat** [badmojr/crosscheck#1]
I noticed an error on https://raw.githubusercontent.com/badmojr/crosscheck/main/errors.txt

They have updated their links not long ago.. Here is an example of what they look like.

https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-hosts.txt

Reference: https://gitlab.com/malware-filter/urlhaus-filter

Cheers Wolf man!! @badmojr

**Comment by badmojr** [comment]
Thank you!

**Comment by RicoHeat** [comment]
> Thank you!

Oh and since we are here.. I was wondering if this list could be considered to the crosschecker since it's their version of the DuckDuckGo's [Tracker Radar](https://github.com/duckduckgo/tracker-radar) project.. They claim that Blokada's list is better at Catching Trackers but with the negative effect of having more false positives or breakage.

Reference: https://gitlab.com/malware-filter/tracking-filter
and this is the list https://malware-filter.gitlab.io/malware-filter/tracking-filter.txt

**Comment by badmojr** [comment]
> > Thank you!
> 
> Oh and since we are here.. I was wondering if this list could be considered to the crosschecker since it's their version of the DuckDuckGo's [Tracker Radar](https://github.com/duckduckgo/tracker-radar) project.. They claim that Blokada's list is better at Catching Trackers but with the negative effect of having more false positives or breakage.
> 
> Reference: https://gitlab.com/malware-filter/tracking-filter and this is the list https://malware-filter.gitlab.io/malware-filter/tracking-filter.txt

This list is for browser-level content blockers. Blokada's is for DNS-level content blockers.

**Comment by krystian3w** [comment]
You can add KAD Hosts - NextDNS added as individual item on the config list for registered accounts.

`https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt`

Works similar to URLhaus with limit to polonized pages (new condition since azet12 entrusted the project to hawkeye hands - without cleaning his bannish without polonisation as long page died e.g. expired whois without revive scam/fraud/malware; other story is trouble with cleaning 2k domains with lost whois expire date).

Then also this allowed for a more rational evaluation of StevenBlack's lecture (to detect how many domains banned it self).
